"""
Configuration package for bot constants and settings
"""

from .constants import (
    TIMEZONE, QUALITIES, SEASONS, REACTIONS, 
    DEFAULT_MAX_BUTTONS, PAGINATION_LIMIT,
    AUTO_DELETE_TIME, SPELL_CHECK_TIMEOUT,
    URL_PATTERN, COMMAND_PATTERN, SPELL_CHECK_PATTERN,
    ERROR_MESSAGES, SUCCESS_MESSAGES, SIZE_UNITS, IMDB_FIELDS
)

__all__ = [
    'TIMEZONE', 'QUALITIES', 'SEASONS', 'REACTIONS',
    'DEFAULT_MAX_BUTTONS', 'PAGINATION_LIMIT',
    'AUTO_DELETE_TIME', 'SPELL_CHECK_TIMEOUT', 
    'URL_PATTERN', 'COMMAND_PATTERN', 'SPELL_CHECK_PATTERN',
    'ERROR_MESSAGES', 'SUCCESS_MESSAGES', 'SIZE_UNITS', 'IMDB_FIELDS'
]
